DROP TABLE TB_SINGER;

CREATE TABLE TB_SINGER (
	S_NO NUMBER PRIMARY KEY NOT NULL,
	S_NAME NVARCHAR2(20) UNIQUE NOT NULL,
	S_MAJOR NVARCHAR2(20) NOT NULL,
	S_DATE DATE NOT NULL,
	S_Agency VARCHAR2(10) NOT NULL,
	S_RETIRE DATE
);

CREATE SEQUENCE SEQ_SNO;

SELECT * FROM TB_SINGER;

INSERT INTO TB_SINGER VALUES (SEQ_SNO.NEXTVAL, '박효신', '야생화', '1999년 11월 4일' ,'허비그하로','');
INSERT INTO TB_SINGER VALUES (SEQ_SNO>NEXTVAL, '아이유', '좋은날')