CREATE TABLE TB_SINGER (
	S_NO NUMBER PRIMARY KEY NOT NULL,
	S_NAME NVARCHAR2(20) NOT NULL,
	S_MAJOR NVARCHAR2(20) NOT NULL,
	S_DATE DATE NOT NULL,
	S_Agency VARCHAR2(10) NOT NULL,
	S_RETIRE DATE NOT NULL,
	S_GENDER CHAR(3)
);

SELECT * FROM TB_SINGER;